css-two-column-layout
Alex-piper/rc1022-code-solutions pull request #20
Opened 2022-10-17 03:39 UTC by Alex-piper

![Screen Shot 2022-10-16 at 8 39 05 PM](https://user-images.githubusercontent.com/110204706/196084313-22aa47c1-7173-47b6-aa0c-977f7a2b9961.png)

2022-10-17 15:33 UTC, Zhiwutian requested changes
Looks great Alex, just a couple small css updates!

2022-10-17 15:33 UTC, Zhiwutian commented on css-two-column-layout/styles.css
> +.one-half {
make sure to have a proper flex basis for this class. We always want to explicitly set a column width

2022-10-17 15:33 UTC, Zhiwutian commented on css-two-column-layout/styles.css
> +.four-fifths {
make sure to include a proper flex basis here

2022-10-17 15:33 UTC, Zhiwutian commented on css-two-column-layout/index.html
> +        <div class="one-fifth">
make sure to include a `one-fifth` class in the CSS with a proper flex basis assigned to it.

2022-10-24 03:12 UTC, Alex-piper commented
<img width="1280" alt="Screen Shot 2022-10-23 at 8 10 49 PM (2)" src="https://user-images.githubusercontent.com/110204706/197441447-3ebed23b-d84a-4ed8-8348-6f9c58eece24.png">

2022-10-25 23:36 UTC, Zhiwutian approved these changes
👍🏼

2022-10-25 23:51 UTC, merged